/**
 * Dynamic Phosphor Icon resolver.
 * Maps icon name strings to Phosphor icon components.
 *
 * Usage in .astro frontmatter:
 *   import { getIcon } from '@/lib/phosphorIcons';
 *   const Icon = getIcon(item.icon);
 * Template:
 *   {Icon && <Icon size={20} weight="light" class="text-primary" />}
 */
import {
  PhStudent,
  PhEnvelope,
  PhPhone,
  PhMapPin,
  PhInstagramLogo,
  PhTwitterLogo,
  PhYoutubeLogo,
  PhTiktokLogo,
  PhUsers,
  PhFilmStrip,
  PhMaskHappy,
  PhMicrophoneStage,
  PhCamera,
  PhPenNib,
  PhMusicNote,
  PhPalette,
  PhGameController,
  PhBookOpen,
  PhHeadphones,
  PhVideo,
  PhLightbulb,
  PhStar,
  PhRocket,
  PhBriefcase,
  PhHeart,
  PhGraduationCap,
  PhBuildings,
  PhHandsClapping,
  PhUsersThree,
  PhGlobe,
  PhLeaf,
  PhClipboardText,
  PhFiles,
  PhPencilSimpleLine,
  PhMegaphone,
  PhPencil,
  PhTrendUp,
  PhChat,
  PhPresentation,
  PhBroadcast,
  PhDeviceMobile,
  PhMagnifyingGlass,
  PhNewspaper,
  // ── Additional icons ──
  PhArrowRight,
  PhArrowLeft,
  PhArrowUp,
  PhArrowDown,
  PhCheck,
  PhCheckCircle,
  PhXCircle,
  PhDownload,
  PhUpload,
  PhLink,
  PhPlayCircle,
  PhPauseCircle,
  PhSmiley,
  PhArticle,
  PhBookmark,
  PhCertificate,
  PhFilePdf,
  PhFileDoc,
  PhClock,
  PhCalendarBlank,
  PhCalendarCheck,
  PhHourglass,
  PhUser,
  PhUserCircle,
  PhUserCircleGear,
  PhUsersFour,
  PhMedalMilitary,
  PhTrophy,
  PhCrown,
  PhChalkboard,
  PhChalkboardTeacher,
  PhNotebook,
  PhCode,
  PhTerminal,
  PhDatabase,
  PhDevices,
  PhChatCircle,
  PhChatCentered,
  PhChatText,
  PhEnvelopeOpen,
  PhPaperPlane,
  PhGear,
  PhKey,
  PhLock,
  PhLockOpen,
  PhTag,
  PhSparkle,
  PhPuzzlePiece,
  PhIdentificationCard,
  PhIdentificationBadge,
  PhShoppingBag,
  PhGlobeStand,
  PhAirplane,
  PhBookBookmark,
  PhBooks,
  // ── Navbar legacy icons ──
  PhEye,
  PhBookOpenText,
  PhTreeStructure,
  PhFlask,
  PhCalendar,
  PhFileText,
  PhMedal,
  PhUserPlus,
} from 'phosphor-icons-astro';

const iconMap: Record<string, any> = {
  // kebab-case names (from editor choices)
  student: PhStudent,
  envelope: PhEnvelope,
  phone: PhPhone,
  'map-pin': PhMapPin,
  'instagram-logo': PhInstagramLogo,
  'twitter-logo': PhTwitterLogo,
  'youtube-logo': PhYoutubeLogo,
  'tiktok-logo': PhTiktokLogo,
  users: PhUsers,
  'film-strip': PhFilmStrip,
  'mask-happy': PhMaskHappy,
  'microphone-stage': PhMicrophoneStage,
  camera: PhCamera,
  'pen-nib': PhPenNib,
  'music-note': PhMusicNote,
  palette: PhPalette,
  'game-controller': PhGameController,
  'book-open': PhBookOpen,
  headphones: PhHeadphones,
  video: PhVideo,
  lightbulb: PhLightbulb,
  star: PhStar,
  rocket: PhRocket,
  briefcase: PhBriefcase,
  heart: PhHeart,
  'graduation-cap': PhGraduationCap,
  buildings: PhBuildings,
  'hands-clapping': PhHandsClapping,
  'users-three': PhUsersThree,
  globe: PhGlobe,
  leaf: PhLeaf,
  'clipboard-text': PhClipboardText,
  files: PhFiles,
  'pencil-simple-line': PhPencilSimpleLine,
  megaphone: PhMegaphone,
  pencil: PhPencil,
  'trend-up': PhTrendUp,
  chat: PhChat,
  presentation: PhPresentation,
  broadcast: PhBroadcast,
  'device-mobile': PhDeviceMobile,
  'magnifying-glass': PhMagnifyingGlass,
  newspaper: PhNewspaper,
  // ── Additional icons ──
  'arrow-right': PhArrowRight,
  'arrow-left': PhArrowLeft,
  'arrow-up': PhArrowUp,
  'arrow-down': PhArrowDown,
  check: PhCheck,
  'check-circle': PhCheckCircle,
  'x-circle': PhXCircle,
  download: PhDownload,
  upload: PhUpload,
  link: PhLink,
  'play-circle': PhPlayCircle,
  'pause-circle': PhPauseCircle,
  smiley: PhSmiley,
  article: PhArticle,
  bookmark: PhBookmark,
  certificate: PhCertificate,
  'file-pdf': PhFilePdf,
  'file-doc': PhFileDoc,
  clock: PhClock,
  'calendar-blank': PhCalendarBlank,
  'calendar-check': PhCalendarCheck,
  hourglass: PhHourglass,
  user: PhUser,
  'user-circle': PhUserCircle,
  'user-circle-gear': PhUserCircleGear,
  'users-four': PhUsersFour,
  award: PhMedalMilitary,
  trophy: PhTrophy,
  crown: PhCrown,
  chalkboard: PhChalkboard,
  'chalkboard-teacher': PhChalkboardTeacher,
  notebook: PhNotebook,
  code: PhCode,
  terminal: PhTerminal,
  database: PhDatabase,
  devices: PhDevices,
  'chat-circle': PhChatCircle,
  'chat-centered': PhChatCentered,
  comment: PhChatText,
  'envelope-open': PhEnvelopeOpen,
  'paper-plane': PhPaperPlane,
  gear: PhGear,
  key: PhKey,
  lock: PhLock,
  'lock-open': PhLockOpen,
  tag: PhTag,
  sparkle: PhSparkle,
  'puzzle-piece': PhPuzzlePiece,
  'identification-card': PhIdentificationCard,
  'identification-badge': PhIdentificationBadge,
  'shopping-bag': PhShoppingBag,
  'globe-stand': PhGlobeStand,
  airplane: PhAirplane,
  'book-bookmark': PhBookBookmark,
  books: PhBooks,
  // ── Navbar legacy icons ──
  eye: PhEye,
  'book-open-text': PhBookOpenText,
  'tree-structure': PhTreeStructure,
  flask: PhFlask,
  calendar: PhCalendar,
  'file-text': PhFileText,
  medal: PhMedal,
  'user-plus': PhUserPlus,
  // PascalCase variants (used in some data from groups/workshops)
  FilmStrip: PhFilmStrip,
  MaskHappy: PhMaskHappy,
  MicrophoneStage: PhMicrophoneStage,
  Camera: PhCamera,
  PenNib: PhPenNib,
  MusicNote: PhMusicNote,
  Palette: PhPalette,
  GameController: PhGameController,
  BookOpen: PhBookOpen,
  Headphones: PhHeadphones,
  Video: PhVideo,
  Lightbulb: PhLightbulb,
  Star: PhStar,
  Rocket: PhRocket,
  Briefcase: PhBriefcase,
  Heart: PhHeart,
  GraduationCap: PhGraduationCap,
  Buildings: PhBuildings,
  HandsClapping: PhHandsClapping,
  UsersThree: PhUsersThree,
  Globe: PhGlobe,
  Leaf: PhLeaf,
  User: PhUsers,
  Users: PhUsers,
};

export function getIcon(name: string) {
  return iconMap[name] || PhStar;
}
